=== CobraUltimate/IntegralsLaboratory/IntegralsLaboratoryWA/web/savedExercisesSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 
    <xs:element name="save">
        
        <xs:complexType mixed="true">
          
            <xs:sequence>
    
                <xs:element name="user" maxOccurs="unbounded">
        
                    <xs:complexType mixed="true">
                        
                           <xs:complexContent>
                
                               <xs:extension base="usertype">
            
                                  <xs:attribute name="id" type="xs:string" />
                                        
                               </xs:extension>
            
                            </xs:complexContent>

                    </xs:complexType>             
        
                </xs:element>

            </xs:sequence>
          
        </xs:complexType>
        
    </xs:element>
    
    
    <xs:complexType mixed="true" name="usertype">
        
        <xs:sequence>
            
          <xs:element name="exercise" maxOccurs="unbounded">
            
          <xs:complexType mixed="true">
              
                        
                           <xs:complexContent>
                
                               <xs:extension base="elemnttype">
            
                                  <xs:attribute name="id" type="xs:integer" />
                                        
                               </xs:extension>
            
                            </xs:complexContent>
              

            </xs:complexType>
          
          </xs:element>
          
        </xs:sequence>
        
    </xs:complexType>
    
    <xs:complexType name="elemnttype" mixed="true">
        
        <xs:sequence>
        
           <xs:element name="expression" type="xs:string"/>
           <xs:element name="xStart" type="xs:integer"/>
           <xs:element name="xFinal" type="xs:integer"/>
           <xs:element name="creationDate" type="xs:date"/>
                
         </xs:sequence>
        
    </xs:complexType>
    
    
        

    
      
    
        
</xs:schema>

=== CobraUltimate/IntegralsLaboratory/IntegralsLaboratoryWA/web/savedExercises.xml
<?xml version="1.0" encoding="UTF-8"?>
<save xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="savedExercisesSchema.xsd">
  
    <user id="Ruben1">
        
        <exercise id="0">
            
            <expression>x*x^3</expression>
            <xStart>223</xStart>
            <xFinal>499</xFinal>
            <creationDate>2019-08-17</creationDate>
            
        </exercise>
        
        <exercise id="1">
            
            <expression>x^3</expression>
            <xStart>2</xStart>
            <xFinal>4</xFinal>
            <creationDate>2019-08-19</creationDate>
            
        </exercise>
        
     </user>
     
     <user id="Ruben1">
        
        <exercise id="1">
            
            <expression>(20+x*x)^3</expression>
            <xStart>22</xStart>
            <xFinal>45</xFinal>
            <creationDate>2019-11-17</creationDate>
            
        </exercise>
        
     </user>
     
    <user id="Ruben2">
        
        <exercise id="0">
            
            <expression>x*x^3</expression>
            <xStart>22323</xStart>
            <xFinal>49299</xFinal>
            <creationDate>2019-11-15</creationDate>
            
        </exercise>
        
    </user>
  
    <user id="Ruben3">
        
        <exercise id="0">
            
            <expression>x*x^3</expression>
            <xStart>22323</xStart>
            <xFinal>49299</xFinal>
            <creationDate>2019-07-07</creationDate>
            
        </exercise>
        
    </user>
    
     <user id="Ruben3">
        
        <exercise id="1">
            
            <expression>x*x^3</expression>
            <xStart>22323</xStart>
            <xFinal>49299</xFinal>
            <creationDate>2019-07-07</creationDate>
            
        </exercise>
        
    </user>
 
 
</save>
